sudo: reqiured
services:
  - docker

before_install:
  - docker build -t omare23/docker-react-vite -f Dockerfile.dev . 

#This is to run our test suite
script:
  - docker run -e CI=true omare23/docker-react-vite npm run test 

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Front-end"
  env: "Front-end-env"
  bucket_name: "elasticbeanstalk-us-east-2-226477727124"
  bucket_path: "Front-end"
  on:
    branch: main
  access_key_id: $AWS_access_key
  secret_access_key: $AWS_secret_key

